/**
 * PRINTER-DATA.JS
 * ================
 * Shared printer series patterns and brand data
 * Used by both ink-finder.js and account.js
 */

'use strict';

const PrinterData = {
    /**
     * Series patterns by brand for categorizing printers
     */
    SERIES_PATTERNS: {
        brother: [
            // Full series prefixes
            { prefix: 'DCP-L', name: 'DCP-L Series (Laser Digital Copier)' },
            { prefix: 'DCP-J', name: 'DCP-J Series (Inkjet Digital Copier)' },
            { prefix: 'DCP-T', name: 'DCP-T Series (Ink Tank)' },
            { prefix: 'DCP', name: 'DCP Series (Digital Copier)' },
            { prefix: 'MFC-L', name: 'MFC-L Series (Laser Multi-Function)' },
            { prefix: 'MFC-J', name: 'MFC-J Series (Inkjet Multi-Function)' },
            { prefix: 'MFC-T', name: 'MFC-T Series (Ink Tank)' },
            { prefix: 'MFC', name: 'MFC Series (Multi-Function)' },
            { prefix: 'HL-L', name: 'HL-L Series (Laser)' },
            { prefix: 'HL', name: 'HL Series (Laser Printer)' },
            { prefix: 'FAX', name: 'FAX Series' },
            { prefix: 'IntelliFax', name: 'IntelliFax Series' },
            { prefix: 'PT-P', name: 'PT-P Series (P-touch Pro)' },
            { prefix: 'PT-D', name: 'PT-D Series (P-touch Desktop)' },
            { prefix: 'PT-E', name: 'PT-E Series (P-touch Industrial)' },
            { prefix: 'PT-H', name: 'PT-H Series (P-touch Handheld)' },
            { prefix: 'PT', name: 'PT Series (P-touch Label)' },
            { prefix: 'QL', name: 'QL Series (Label Printer)' },
            { prefix: 'TD', name: 'TD Series (Thermal Direct)' },
            { prefix: 'ADS', name: 'ADS Series (Document Scanner)' },
            { prefix: 'RJ', name: 'RJ Series (Portable Printer)' },
            { prefix: 'PJ', name: 'PJ Series (PocketJet)' },
            { prefix: 'MW', name: 'MW Series (Mobile Printer)' },
            { prefix: 'TJ', name: 'TJ Series (Industrial Printer)' },
            { prefix: 'DS', name: 'DS Series (Document Scanner)' },
            { prefix: 'VC', name: 'VC Series (Color Laser)' }
        ],
        canon: [
            // Full name prefixes (check first)
            { prefix: 'PIXMA TS', name: 'PIXMA TS Series' },
            { prefix: 'PIXMA TR', name: 'PIXMA TR Series' },
            { prefix: 'PIXMA G', name: 'PIXMA G Series (MegaTank)' },
            { prefix: 'PIXMA MG', name: 'PIXMA MG Series' },
            { prefix: 'PIXMA MX', name: 'PIXMA MX Series' },
            { prefix: 'PIXMA iP', name: 'PIXMA iP Series' },
            { prefix: 'PIXMA iX', name: 'PIXMA iX Series' },
            { prefix: 'PIXMA PRO', name: 'PIXMA PRO Series' },
            { prefix: 'PIXMA MP', name: 'PIXMA MP Series' },
            { prefix: 'PIXMA E', name: 'PIXMA E Series' },
            { prefix: 'PIXMA', name: 'PIXMA Series' },
            { prefix: 'MAXIFY GX', name: 'MAXIFY GX Series (MegaTank)' },
            { prefix: 'MAXIFY MB', name: 'MAXIFY MB Series' },
            { prefix: 'MAXIFY iB', name: 'MAXIFY iB Series' },
            { prefix: 'MAXIFY', name: 'MAXIFY Series' },
            { prefix: 'imageCLASS MF', name: 'imageCLASS MF Series (MFP)' },
            { prefix: 'imageCLASS LBP', name: 'imageCLASS LBP Series' },
            { prefix: 'imageCLASS D', name: 'imageCLASS D Series' },
            { prefix: 'imageCLASS', name: 'imageCLASS Series' },
            { prefix: 'i-SENSYS MF', name: 'i-SENSYS MF Series (MFP)' },
            { prefix: 'i-SENSYS LBP', name: 'i-SENSYS LBP Series' },
            { prefix: 'i-SENSYS', name: 'i-SENSYS Series' },
            { prefix: 'imageRUNNER ADVANCE', name: 'imageRUNNER ADVANCE Series' },
            { prefix: 'imageRUNNER', name: 'imageRUNNER Series' },
            { prefix: 'imagePROGRAF', name: 'imagePROGRAF Series' },
            { prefix: 'SELPHY', name: 'SELPHY Series (Compact Photo)' },
            // Short form prefixes (for database entries without full series name)
            { prefix: 'TS', name: 'PIXMA TS Series' },
            { prefix: 'TR', name: 'PIXMA TR Series' },
            { prefix: 'MG', name: 'PIXMA MG Series' },
            { prefix: 'MX', name: 'PIXMA MX Series' },
            { prefix: 'MP', name: 'PIXMA MP Series' },
            { prefix: 'iP', name: 'PIXMA iP Series' },
            { prefix: 'iX', name: 'PIXMA iX Series' },
            { prefix: 'PRO-', name: 'PIXMA PRO Series' },
            { prefix: 'G1', name: 'PIXMA G Series (MegaTank)' },
            { prefix: 'G2', name: 'PIXMA G Series (MegaTank)' },
            { prefix: 'G3', name: 'PIXMA G Series (MegaTank)' },
            { prefix: 'G4', name: 'PIXMA G Series (MegaTank)' },
            { prefix: 'G5', name: 'PIXMA G Series (MegaTank)' },
            { prefix: 'G6', name: 'PIXMA G Series (MegaTank)' },
            { prefix: 'G7', name: 'PIXMA G Series (MegaTank)' },
            { prefix: 'GX', name: 'MAXIFY GX Series (MegaTank)' },
            { prefix: 'MB', name: 'MAXIFY MB Series' },
            { prefix: 'iB', name: 'MAXIFY iB Series' },
            { prefix: 'MF', name: 'imageCLASS MF Series (MFP)' },
            { prefix: 'LBP', name: 'imageCLASS LBP Series' },
            { prefix: 'iR-ADV', name: 'imageRUNNER ADVANCE Series' },
            { prefix: 'iR', name: 'imageRUNNER Series' },
            { prefix: 'iPF', name: 'imagePROGRAF Series' },
            { prefix: 'CP', name: 'SELPHY Series (Compact Photo)' },
            { prefix: 'ES', name: 'SELPHY ES Series' },
            { prefix: 'E', name: 'PIXMA E Series' },
            { prefix: 'i-SENSYS', name: 'i-SENSYS Series' },
            { prefix: 'BJC', name: 'BJC Series (BubbleJet)' },
            { prefix: 'BJ', name: 'BJ Series (BubbleJet)' },
            { prefix: 'S', name: 'S Series (Photo)' },
            { prefix: 'CanoScan', name: 'CanoScan Series (Scanner)' }
        ],
        epson: [
            // Full name prefixes
            { prefix: 'Expression Home XP', name: 'Expression Home XP Series' },
            { prefix: 'Expression Photo XP', name: 'Expression Photo XP Series' },
            { prefix: 'Expression Premium XP', name: 'Expression Premium XP Series' },
            { prefix: 'Expression Home', name: 'Expression Home Series' },
            { prefix: 'Expression Photo', name: 'Expression Photo Series' },
            { prefix: 'Expression Premium', name: 'Expression Premium Series' },
            { prefix: 'Expression', name: 'Expression Series' },
            { prefix: 'EcoTank ET', name: 'EcoTank ET Series' },
            { prefix: 'EcoTank L', name: 'EcoTank L Series' },
            { prefix: 'EcoTank', name: 'EcoTank Series' },
            { prefix: 'WorkForce Pro WF', name: 'WorkForce Pro Series' },
            { prefix: 'WorkForce Pro', name: 'WorkForce Pro Series' },
            { prefix: 'WorkForce WF', name: 'WorkForce Series' },
            { prefix: 'WorkForce', name: 'WorkForce Series' },
            { prefix: 'Stylus Photo', name: 'Stylus Photo Series' },
            { prefix: 'Stylus Pro', name: 'Stylus Pro Series' },
            { prefix: 'Stylus Office', name: 'Stylus Office Series' },
            { prefix: 'Stylus CX', name: 'Stylus CX Series' },
            { prefix: 'Stylus NX', name: 'Stylus NX Series' },
            { prefix: 'Stylus SX', name: 'Stylus SX Series' },
            { prefix: 'Stylus TX', name: 'Stylus TX Series' },
            { prefix: 'Stylus', name: 'Stylus Series' },
            { prefix: 'SureColor SC', name: 'SureColor Series' },
            { prefix: 'SureColor', name: 'SureColor Series' },
            { prefix: 'Artisan', name: 'Artisan Series' },
            { prefix: 'PictureMate', name: 'PictureMate Series' },
            // Short form prefixes
            { prefix: 'XP-', name: 'XP Series (Expression)' },
            { prefix: 'WF-', name: 'WF Series (WorkForce)' },
            { prefix: 'ET-', name: 'ET Series (EcoTank)' },
            { prefix: 'L1', name: 'L Series (EcoTank)' },
            { prefix: 'L3', name: 'L Series (EcoTank)' },
            { prefix: 'L4', name: 'L Series (EcoTank)' },
            { prefix: 'L5', name: 'L Series (EcoTank)' },
            { prefix: 'L6', name: 'L Series (EcoTank)' },
            { prefix: 'L8', name: 'L Series (EcoTank)' },
            { prefix: 'L', name: 'L Series (EcoTank)' },
            { prefix: 'SC-', name: 'SC Series (SureColor)' },
            { prefix: 'PM-', name: 'PM Series (PictureMate)' },
            { prefix: 'EP-', name: 'EP Series' },
            { prefix: 'CX', name: 'Stylus CX Series' },
            { prefix: 'NX', name: 'Stylus NX Series' },
            { prefix: 'SX', name: 'Stylus SX Series' },
            { prefix: 'TX', name: 'Stylus TX Series' },
            { prefix: 'R', name: 'Stylus Photo R Series' },
            { prefix: 'RX', name: 'Stylus Photo RX Series' },
            { prefix: 'PX', name: 'PX Series' },
            { prefix: 'BX', name: 'BX Series (Office)' },
            { prefix: 'DX', name: 'DX Series' },
            { prefix: 'T', name: 'T Series' },
            { prefix: 'C', name: 'C Series (Stylus Color)' }
        ],
        hp: [
            // Full name prefixes
            { prefix: 'DeskJet Plus', name: 'DeskJet Plus Series' },
            { prefix: 'DeskJet Ink Advantage', name: 'DeskJet Ink Advantage Series' },
            { prefix: 'DeskJet', name: 'DeskJet Series' },
            { prefix: 'Deskjet', name: 'DeskJet Series' },
            { prefix: 'ENVY Pro', name: 'ENVY Pro Series' },
            { prefix: 'ENVY Inspire', name: 'ENVY Inspire Series' },
            { prefix: 'ENVY Photo', name: 'ENVY Photo Series' },
            { prefix: 'ENVY', name: 'ENVY Series' },
            { prefix: 'Envy', name: 'ENVY Series' },
            { prefix: 'OfficeJet Pro', name: 'OfficeJet Pro Series' },
            { prefix: 'OfficeJet', name: 'OfficeJet Series' },
            { prefix: 'Officejet Pro', name: 'OfficeJet Pro Series' },
            { prefix: 'Officejet', name: 'OfficeJet Series' },
            { prefix: 'Color LaserJet Pro MFP', name: 'Color LaserJet Pro MFP Series' },
            { prefix: 'Color LaserJet Pro', name: 'Color LaserJet Pro Series' },
            { prefix: 'Color LaserJet MFP', name: 'Color LaserJet MFP Series' },
            { prefix: 'Color LaserJet', name: 'Color LaserJet Series' },
            { prefix: 'LaserJet Pro MFP', name: 'LaserJet Pro MFP Series' },
            { prefix: 'LaserJet Pro', name: 'LaserJet Pro Series' },
            { prefix: 'LaserJet Enterprise MFP', name: 'LaserJet Enterprise MFP Series' },
            { prefix: 'LaserJet Enterprise', name: 'LaserJet Enterprise Series' },
            { prefix: 'LaserJet MFP', name: 'LaserJet MFP Series' },
            { prefix: 'LaserJet', name: 'LaserJet Series' },
            { prefix: 'Laserjet', name: 'LaserJet Series' },
            { prefix: 'PhotoSmart', name: 'PhotoSmart Series' },
            { prefix: 'Photosmart', name: 'PhotoSmart Series' },
            { prefix: 'Smart Tank Plus', name: 'Smart Tank Plus Series' },
            { prefix: 'Smart Tank', name: 'Smart Tank Series' },
            { prefix: 'Ink Tank Wireless', name: 'Ink Tank Wireless Series' },
            { prefix: 'Ink Tank', name: 'Ink Tank Series' },
            { prefix: 'PageWide Pro', name: 'PageWide Pro Series' },
            { prefix: 'PageWide', name: 'PageWide Series' },
            { prefix: 'DesignJet', name: 'DesignJet Series' },
            { prefix: 'PSC', name: 'PSC Series' },
            { prefix: 'Neverstop', name: 'Neverstop Laser Series' },
            // Short form / model number prefixes
            { prefix: 'DJ', name: 'DeskJet Series' },
            { prefix: 'OJ Pro', name: 'OfficeJet Pro Series' },
            { prefix: 'OJ', name: 'OfficeJet Series' },
            { prefix: 'LJ Pro MFP', name: 'LaserJet Pro MFP Series' },
            { prefix: 'LJ Pro', name: 'LaserJet Pro Series' },
            { prefix: 'LJ MFP', name: 'LaserJet MFP Series' },
            { prefix: 'LJ', name: 'LaserJet Series' },
            { prefix: 'CLJ Pro MFP', name: 'Color LaserJet Pro MFP Series' },
            { prefix: 'CLJ Pro', name: 'Color LaserJet Pro Series' },
            { prefix: 'CLJ MFP', name: 'Color LaserJet MFP Series' },
            { prefix: 'CLJ', name: 'Color LaserJet Series' },
            { prefix: 'PS', name: 'PhotoSmart Series' },
            { prefix: 'CP', name: 'Color LaserJet CP Series' },
            { prefix: 'CM', name: 'Color LaserJet CM Series' },
            { prefix: 'M1', name: 'LaserJet M Series' },
            { prefix: 'M2', name: 'LaserJet M Series' },
            { prefix: 'M4', name: 'LaserJet M Series' },
            { prefix: 'M5', name: 'LaserJet M Series' },
            { prefix: 'M6', name: 'LaserJet M Series' },
            { prefix: 'P1', name: 'LaserJet P Series' },
            { prefix: 'P2', name: 'LaserJet P Series' },
            { prefix: 'P3', name: 'LaserJet P Series' },
            { prefix: 'P4', name: 'LaserJet P Series' },
            { prefix: '1', name: 'DeskJet 1000 Series' },
            { prefix: '2', name: 'DeskJet 2000 Series' },
            { prefix: '3', name: 'DeskJet 3000 Series' },
            { prefix: '4', name: 'DeskJet 4000 Series' },
            { prefix: '5', name: 'DeskJet/ENVY 5000 Series' },
            { prefix: '6', name: 'OfficeJet 6000 Series' },
            { prefix: '7', name: 'OfficeJet 7000 Series' },
            { prefix: '8', name: 'OfficeJet Pro 8000 Series' },
            { prefix: '9', name: 'OfficeJet Pro 9000 Series' }
        ],
        samsung: [
            // Full name prefixes
            { prefix: 'ProXpress SL-C', name: 'ProXpress Color Series' },
            { prefix: 'ProXpress SL-M', name: 'ProXpress Mono Series' },
            { prefix: 'ProXpress C', name: 'ProXpress Color Series' },
            { prefix: 'ProXpress M', name: 'ProXpress Mono Series' },
            { prefix: 'ProXpress', name: 'ProXpress Series' },
            { prefix: 'Xpress SL-C', name: 'Xpress Color Series' },
            { prefix: 'Xpress SL-M', name: 'Xpress Mono Series' },
            { prefix: 'Xpress C', name: 'Xpress Color Series' },
            { prefix: 'Xpress M', name: 'Xpress Mono Series' },
            { prefix: 'Xpress', name: 'Xpress Series' },
            // Short form prefixes
            { prefix: 'SL-C48', name: 'Xpress Color Series' },
            { prefix: 'SL-C47', name: 'Xpress Color Series' },
            { prefix: 'SL-C46', name: 'Xpress Color Series' },
            { prefix: 'SL-C43', name: 'Xpress Color Series' },
            { prefix: 'SL-C41', name: 'Xpress Color Series' },
            { prefix: 'SL-C', name: 'SL-C Series (Color)' },
            { prefix: 'SL-M48', name: 'ProXpress Mono Series' },
            { prefix: 'SL-M46', name: 'ProXpress Mono Series' },
            { prefix: 'SL-M42', name: 'ProXpress Mono Series' },
            { prefix: 'SL-M40', name: 'Xpress Mono Series' },
            { prefix: 'SL-M38', name: 'Xpress Mono Series' },
            { prefix: 'SL-M28', name: 'Xpress Mono Series' },
            { prefix: 'SL-M26', name: 'Xpress Mono Series' },
            { prefix: 'SL-M20', name: 'Xpress Mono Series' },
            { prefix: 'SL-M', name: 'SL-M Series (Mono)' },
            { prefix: 'SL', name: 'SL Series' },
            { prefix: 'CLX-9', name: 'CLX-9000 Series (Color MFP)' },
            { prefix: 'CLX-6', name: 'CLX-6000 Series (Color MFP)' },
            { prefix: 'CLX-4', name: 'CLX-4000 Series (Color MFP)' },
            { prefix: 'CLX-3', name: 'CLX-3000 Series (Color MFP)' },
            { prefix: 'CLX', name: 'CLX Series (Color MFP)' },
            { prefix: 'CLP-7', name: 'CLP-700 Series (Color)' },
            { prefix: 'CLP-6', name: 'CLP-600 Series (Color)' },
            { prefix: 'CLP-5', name: 'CLP-500 Series (Color)' },
            { prefix: 'CLP-4', name: 'CLP-400 Series (Color)' },
            { prefix: 'CLP-3', name: 'CLP-300 Series (Color)' },
            { prefix: 'CLP', name: 'CLP Series (Color Laser)' },
            { prefix: 'SCX-6', name: 'SCX-6000 Series (Mono MFP)' },
            { prefix: 'SCX-5', name: 'SCX-5000 Series (Mono MFP)' },
            { prefix: 'SCX-4', name: 'SCX-4000 Series (Mono MFP)' },
            { prefix: 'SCX-3', name: 'SCX-3000 Series (Mono MFP)' },
            { prefix: 'SCX', name: 'SCX Series (Mono MFP)' },
            { prefix: 'ML-3', name: 'ML-3000 Series (Mono)' },
            { prefix: 'ML-2', name: 'ML-2000 Series (Mono)' },
            { prefix: 'ML-1', name: 'ML-1000 Series (Mono)' },
            { prefix: 'ML', name: 'ML Series (Mono Laser)' },
            { prefix: 'SF', name: 'SF Series (Fax)' },
            { prefix: 'M20', name: 'Xpress M20 Series' },
            { prefix: 'M26', name: 'Xpress M26 Series' },
            { prefix: 'M28', name: 'Xpress M28 Series' },
            { prefix: 'C48', name: 'Xpress C48 Series' },
            { prefix: 'C43', name: 'Xpress C43 Series' }
        ],
        lexmark: [
            // Current series (most specific first)
            { prefix: 'CX9', name: 'CX900 Series (Color MFP)' },
            { prefix: 'CX8', name: 'CX800 Series (Color MFP)' },
            { prefix: 'CX7', name: 'CX700 Series (Color MFP)' },
            { prefix: 'CX6', name: 'CX600 Series (Color MFP)' },
            { prefix: 'CX5', name: 'CX500 Series (Color MFP)' },
            { prefix: 'CX4', name: 'CX400 Series (Color MFP)' },
            { prefix: 'CX3', name: 'CX300 Series (Color MFP)' },
            { prefix: 'CX', name: 'CX Series (Color MFP)' },
            { prefix: 'CS9', name: 'CS900 Series (Color)' },
            { prefix: 'CS7', name: 'CS700 Series (Color)' },
            { prefix: 'CS5', name: 'CS500 Series (Color)' },
            { prefix: 'CS4', name: 'CS400 Series (Color)' },
            { prefix: 'CS3', name: 'CS300 Series (Color)' },
            { prefix: 'CS', name: 'CS Series (Color Laser)' },
            { prefix: 'MX9', name: 'MX900 Series (Mono MFP)' },
            { prefix: 'MX8', name: 'MX800 Series (Mono MFP)' },
            { prefix: 'MX7', name: 'MX700 Series (Mono MFP)' },
            { prefix: 'MX6', name: 'MX600 Series (Mono MFP)' },
            { prefix: 'MX5', name: 'MX500 Series (Mono MFP)' },
            { prefix: 'MX4', name: 'MX400 Series (Mono MFP)' },
            { prefix: 'MX3', name: 'MX300 Series (Mono MFP)' },
            { prefix: 'MX', name: 'MX Series (Mono MFP)' },
            { prefix: 'MS9', name: 'MS900 Series (Mono)' },
            { prefix: 'MS8', name: 'MS800 Series (Mono)' },
            { prefix: 'MS7', name: 'MS700 Series (Mono)' },
            { prefix: 'MS6', name: 'MS600 Series (Mono)' },
            { prefix: 'MS5', name: 'MS500 Series (Mono)' },
            { prefix: 'MS4', name: 'MS400 Series (Mono)' },
            { prefix: 'MS3', name: 'MS300 Series (Mono)' },
            { prefix: 'MS', name: 'MS Series (Mono Laser)' },
            { prefix: 'MB', name: 'MB Series (Mono MFP)' },
            { prefix: 'MC', name: 'MC Series (Color MFP)' },
            { prefix: 'XC', name: 'XC Series (Color MFP)' },
            { prefix: 'XM', name: 'XM Series (Mono MFP)' },
            { prefix: 'X9', name: 'X900 Series (MFP)' },
            { prefix: 'X7', name: 'X700 Series (MFP)' },
            { prefix: 'X6', name: 'X600 Series (MFP)' },
            { prefix: 'X5', name: 'X500 Series (MFP)' },
            { prefix: 'X4', name: 'X400 Series (MFP)' },
            { prefix: 'X3', name: 'X300 Series (MFP)' },
            { prefix: 'X2', name: 'X200 Series (MFP)' },
            { prefix: 'X', name: 'X Series (Legacy)' },
            { prefix: 'E4', name: 'E400 Series (Entry)' },
            { prefix: 'E3', name: 'E300 Series (Entry)' },
            { prefix: 'E2', name: 'E200 Series (Entry)' },
            { prefix: 'E', name: 'E Series (Entry)' },
            { prefix: 'C9', name: 'C900 Series (Color)' },
            { prefix: 'C7', name: 'C700 Series (Color)' },
            { prefix: 'C5', name: 'C500 Series (Color)' },
            { prefix: 'C4', name: 'C400 Series (Color)' },
            { prefix: 'C3', name: 'C300 Series (Color)' },
            { prefix: 'C', name: 'C Series (Color)' },
            { prefix: 'B3', name: 'B300 Series (Mono)' },
            { prefix: 'B2', name: 'B200 Series (Mono)' },
            { prefix: 'B', name: 'B Series (Mono)' },
            { prefix: 'T6', name: 'T600 Series (Mono)' },
            { prefix: 'T5', name: 'T500 Series (Mono)' },
            { prefix: 'T4', name: 'T400 Series (Mono)' },
            { prefix: 'T', name: 'T Series (Mono)' },
            { prefix: 'W8', name: 'W800 Series (Wide Format)' },
            { prefix: 'W', name: 'W Series (Wide Format)' }
        ],
        oki: [
            // MFP series
            { prefix: 'MC8', name: 'MC800 Series (Color MFP)' },
            { prefix: 'MC7', name: 'MC700 Series (Color MFP)' },
            { prefix: 'MC5', name: 'MC500 Series (Color MFP)' },
            { prefix: 'MC3', name: 'MC300 Series (Color MFP)' },
            { prefix: 'MC', name: 'MC Series (Color MFP)' },
            { prefix: 'MB7', name: 'MB700 Series (Mono MFP)' },
            { prefix: 'MB5', name: 'MB500 Series (Mono MFP)' },
            { prefix: 'MB4', name: 'MB400 Series (Mono MFP)' },
            { prefix: 'MB', name: 'MB Series (Mono MFP)' },
            // Color printers
            { prefix: 'C9', name: 'C900 Series (Color)' },
            { prefix: 'C8', name: 'C800 Series (Color)' },
            { prefix: 'C7', name: 'C700 Series (Color)' },
            { prefix: 'C6', name: 'C600 Series (Color)' },
            { prefix: 'C5', name: 'C500 Series (Color)' },
            { prefix: 'C3', name: 'C300 Series (Color)' },
            { prefix: 'C', name: 'C Series (Color)' },
            // Mono printers
            { prefix: 'B9', name: 'B900 Series (Mono)' },
            { prefix: 'B8', name: 'B800 Series (Mono)' },
            { prefix: 'B7', name: 'B700 Series (Mono)' },
            { prefix: 'B5', name: 'B500 Series (Mono)' },
            { prefix: 'B4', name: 'B400 Series (Mono)' },
            { prefix: 'B', name: 'B Series (Mono)' },
            // Executive and Pro series
            { prefix: 'ES94', name: 'ES9400 Series (Color)' },
            { prefix: 'ES84', name: 'ES8400 Series (Color)' },
            { prefix: 'ES', name: 'ES Series (Executive)' },
            { prefix: 'Pro9', name: 'Pro9000 Series' },
            { prefix: 'Pro8', name: 'Pro8000 Series' },
            { prefix: 'Pro', name: 'Pro Series' },
            // Label printers
            { prefix: 'Pro1', name: 'Pro1000 Series (Label)' }
        ],
        'fuji-xerox': [
            // DocuPrint series (most specific first)
            { prefix: 'DocuPrint CP5', name: 'DocuPrint CP500 Series (Color)' },
            { prefix: 'DocuPrint CP4', name: 'DocuPrint CP400 Series (Color)' },
            { prefix: 'DocuPrint CP3', name: 'DocuPrint CP300 Series (Color)' },
            { prefix: 'DocuPrint CP2', name: 'DocuPrint CP200 Series (Color)' },
            { prefix: 'DocuPrint CP1', name: 'DocuPrint CP100 Series (Color)' },
            { prefix: 'DocuPrint CP', name: 'DocuPrint CP Series (Color)' },
            { prefix: 'DocuPrint CM5', name: 'DocuPrint CM500 Series (Color MFP)' },
            { prefix: 'DocuPrint CM4', name: 'DocuPrint CM400 Series (Color MFP)' },
            { prefix: 'DocuPrint CM3', name: 'DocuPrint CM300 Series (Color MFP)' },
            { prefix: 'DocuPrint CM2', name: 'DocuPrint CM200 Series (Color MFP)' },
            { prefix: 'DocuPrint CM1', name: 'DocuPrint CM100 Series (Color MFP)' },
            { prefix: 'DocuPrint CM', name: 'DocuPrint CM Series (Color MFP)' },
            { prefix: 'DocuPrint P5', name: 'DocuPrint P500 Series (Mono)' },
            { prefix: 'DocuPrint P4', name: 'DocuPrint P400 Series (Mono)' },
            { prefix: 'DocuPrint P3', name: 'DocuPrint P300 Series (Mono)' },
            { prefix: 'DocuPrint P2', name: 'DocuPrint P200 Series (Mono)' },
            { prefix: 'DocuPrint P1', name: 'DocuPrint P100 Series (Mono)' },
            { prefix: 'DocuPrint P', name: 'DocuPrint P Series (Mono)' },
            { prefix: 'DocuPrint M5', name: 'DocuPrint M500 Series (Mono MFP)' },
            { prefix: 'DocuPrint M4', name: 'DocuPrint M400 Series (Mono MFP)' },
            { prefix: 'DocuPrint M3', name: 'DocuPrint M300 Series (Mono MFP)' },
            { prefix: 'DocuPrint M2', name: 'DocuPrint M200 Series (Mono MFP)' },
            { prefix: 'DocuPrint M1', name: 'DocuPrint M100 Series (Mono MFP)' },
            { prefix: 'DocuPrint M', name: 'DocuPrint M Series (Mono MFP)' },
            { prefix: 'DocuPrint C', name: 'DocuPrint C Series' },
            { prefix: 'DocuPrint', name: 'DocuPrint Series' },
            // DocuCentre series
            { prefix: 'DocuCentre-VII', name: 'DocuCentre-VII Series' },
            { prefix: 'DocuCentre-VI', name: 'DocuCentre-VI Series' },
            { prefix: 'DocuCentre-V', name: 'DocuCentre-V Series' },
            { prefix: 'DocuCentre-IV', name: 'DocuCentre-IV Series' },
            { prefix: 'DocuCentre SC', name: 'DocuCentre SC Series' },
            { prefix: 'DocuCentre S', name: 'DocuCentre S Series' },
            { prefix: 'DocuCentre', name: 'DocuCentre Series' },
            // ApeosPort series
            { prefix: 'ApeosPort-VII', name: 'ApeosPort-VII Series' },
            { prefix: 'ApeosPort-VI', name: 'ApeosPort-VI Series' },
            { prefix: 'ApeosPort-V', name: 'ApeosPort-V Series' },
            { prefix: 'ApeosPort-IV', name: 'ApeosPort-IV Series' },
            { prefix: 'ApeosPort', name: 'ApeosPort Series' },
            { prefix: 'Apeos C', name: 'Apeos C Series (Color)' },
            { prefix: 'Apeos', name: 'Apeos Series' },
            // Xerox branded (after Fuji Xerox split)
            { prefix: 'VersaLink C', name: 'VersaLink C Series (Color)' },
            { prefix: 'VersaLink B', name: 'VersaLink B Series (Mono)' },
            { prefix: 'VersaLink', name: 'VersaLink Series' },
            { prefix: 'AltaLink C', name: 'AltaLink C Series (Color MFP)' },
            { prefix: 'AltaLink B', name: 'AltaLink B Series (Mono MFP)' },
            { prefix: 'AltaLink', name: 'AltaLink Series' },
            { prefix: 'Phaser 7', name: 'Phaser 7000 Series' },
            { prefix: 'Phaser 6', name: 'Phaser 6000 Series' },
            { prefix: 'Phaser 5', name: 'Phaser 5000 Series' },
            { prefix: 'Phaser 4', name: 'Phaser 4000 Series' },
            { prefix: 'Phaser 3', name: 'Phaser 3000 Series' },
            { prefix: 'Phaser', name: 'Phaser Series' },
            { prefix: 'WorkCentre 7', name: 'WorkCentre 7000 Series' },
            { prefix: 'WorkCentre 6', name: 'WorkCentre 6000 Series' },
            { prefix: 'WorkCentre 5', name: 'WorkCentre 5000 Series' },
            { prefix: 'WorkCentre 3', name: 'WorkCentre 3000 Series' },
            { prefix: 'WorkCentre', name: 'WorkCentre Series' },
            // Short form prefixes
            { prefix: 'CP', name: 'DocuPrint CP Series (Color)' },
            { prefix: 'CM', name: 'DocuPrint CM Series (Color MFP)' },
            { prefix: 'SC', name: 'DocuCentre SC Series' }
        ],
        kyocera: [
            // ECOSYS series (most specific first)
            { prefix: 'ECOSYS P80', name: 'ECOSYS P8000 Series (Mono)' },
            { prefix: 'ECOSYS P70', name: 'ECOSYS P7000 Series (Color)' },
            { prefix: 'ECOSYS P60', name: 'ECOSYS P6000 Series (Color)' },
            { prefix: 'ECOSYS P50', name: 'ECOSYS P5000 Series (Color)' },
            { prefix: 'ECOSYS P40', name: 'ECOSYS P4000 Series (Mono)' },
            { prefix: 'ECOSYS P35', name: 'ECOSYS P3500 Series (Mono)' },
            { prefix: 'ECOSYS P30', name: 'ECOSYS P3000 Series (Mono)' },
            { prefix: 'ECOSYS P22', name: 'ECOSYS P2200 Series (Mono)' },
            { prefix: 'ECOSYS P21', name: 'ECOSYS P2100 Series (Mono)' },
            { prefix: 'ECOSYS P20', name: 'ECOSYS P2000 Series (Mono)' },
            { prefix: 'ECOSYS P', name: 'ECOSYS P Series (Printer)' },
            { prefix: 'ECOSYS M82', name: 'ECOSYS M8200 Series (Color MFP)' },
            { prefix: 'ECOSYS M81', name: 'ECOSYS M8100 Series (Color MFP)' },
            { prefix: 'ECOSYS M65', name: 'ECOSYS M6500 Series (Color MFP)' },
            { prefix: 'ECOSYS M64', name: 'ECOSYS M6400 Series (Color MFP)' },
            { prefix: 'ECOSYS M62', name: 'ECOSYS M6200 Series (Color MFP)' },
            { prefix: 'ECOSYS M55', name: 'ECOSYS M5500 Series (Color MFP)' },
            { prefix: 'ECOSYS M45', name: 'ECOSYS M4500 Series (Mono MFP)' },
            { prefix: 'ECOSYS M40', name: 'ECOSYS M4000 Series (Mono MFP)' },
            { prefix: 'ECOSYS M35', name: 'ECOSYS M3500 Series (Mono MFP)' },
            { prefix: 'ECOSYS M30', name: 'ECOSYS M3000 Series (Mono MFP)' },
            { prefix: 'ECOSYS M26', name: 'ECOSYS M2600 Series (Mono MFP)' },
            { prefix: 'ECOSYS M25', name: 'ECOSYS M2500 Series (Mono MFP)' },
            { prefix: 'ECOSYS M21', name: 'ECOSYS M2100 Series (Mono MFP)' },
            { prefix: 'ECOSYS M20', name: 'ECOSYS M2000 Series (Mono MFP)' },
            { prefix: 'ECOSYS M', name: 'ECOSYS M Series (MFP)' },
            { prefix: 'ECOSYS', name: 'ECOSYS Series' },
            // TASKalfa series
            { prefix: 'TASKalfa 80', name: 'TASKalfa 8000 Series' },
            { prefix: 'TASKalfa 70', name: 'TASKalfa 7000 Series' },
            { prefix: 'TASKalfa 60', name: 'TASKalfa 6000 Series' },
            { prefix: 'TASKalfa 55', name: 'TASKalfa 5500 Series' },
            { prefix: 'TASKalfa 50', name: 'TASKalfa 5000 Series' },
            { prefix: 'TASKalfa 40', name: 'TASKalfa 4000 Series' },
            { prefix: 'TASKalfa 35', name: 'TASKalfa 3500 Series' },
            { prefix: 'TASKalfa 30', name: 'TASKalfa 3000 Series' },
            { prefix: 'TASKalfa 25', name: 'TASKalfa 2500 Series' },
            { prefix: 'TASKalfa 20', name: 'TASKalfa 2000 Series' },
            { prefix: 'TASKalfa', name: 'TASKalfa Series' },
            // Legacy FS series
            { prefix: 'FS-C8', name: 'FS-C8000 Series (Color)' },
            { prefix: 'FS-C5', name: 'FS-C5000 Series (Color)' },
            { prefix: 'FS-C2', name: 'FS-C2000 Series (Color)' },
            { prefix: 'FS-C', name: 'FS-C Series (Color)' },
            { prefix: 'FS-4', name: 'FS-4000 Series (Mono)' },
            { prefix: 'FS-3', name: 'FS-3000 Series (Mono)' },
            { prefix: 'FS-2', name: 'FS-2000 Series (Mono)' },
            { prefix: 'FS-1', name: 'FS-1000 Series (Mono)' },
            { prefix: 'FS', name: 'FS Series' },
            // KM series
            { prefix: 'KM-C', name: 'KM-C Series (Color)' },
            { prefix: 'KM', name: 'KM Series' },
            // Short form prefixes (for models stored without ECOSYS prefix)
            { prefix: 'P80', name: 'ECOSYS P8000 Series (Mono)' },
            { prefix: 'P70', name: 'ECOSYS P7000 Series (Color)' },
            { prefix: 'P60', name: 'ECOSYS P6000 Series (Color)' },
            { prefix: 'P50', name: 'ECOSYS P5000 Series (Color)' },
            { prefix: 'P40', name: 'ECOSYS P4000 Series (Mono)' },
            { prefix: 'P35', name: 'ECOSYS P3500 Series (Mono)' },
            { prefix: 'P30', name: 'ECOSYS P3000 Series (Mono)' },
            { prefix: 'P22', name: 'ECOSYS P2200 Series (Mono)' },
            { prefix: 'P21', name: 'ECOSYS P2100 Series (Mono)' },
            { prefix: 'P20', name: 'ECOSYS P2000 Series (Mono)' },
            { prefix: 'P', name: 'P Series (ECOSYS)' },
            { prefix: 'M82', name: 'ECOSYS M8200 Series (Color MFP)' },
            { prefix: 'M81', name: 'ECOSYS M8100 Series (Color MFP)' },
            { prefix: 'M65', name: 'ECOSYS M6500 Series (Color MFP)' },
            { prefix: 'M64', name: 'ECOSYS M6400 Series (Color MFP)' },
            { prefix: 'M55', name: 'ECOSYS M5500 Series (Color MFP)' },
            { prefix: 'M45', name: 'ECOSYS M4500 Series (Mono MFP)' },
            { prefix: 'M40', name: 'ECOSYS M4000 Series (Mono MFP)' },
            { prefix: 'M35', name: 'ECOSYS M3500 Series (Mono MFP)' },
            { prefix: 'M30', name: 'ECOSYS M3000 Series (Mono MFP)' },
            { prefix: 'M26', name: 'ECOSYS M2600 Series (Mono MFP)' },
            { prefix: 'M25', name: 'ECOSYS M2500 Series (Mono MFP)' },
            { prefix: 'M21', name: 'ECOSYS M2100 Series (Mono MFP)' },
            { prefix: 'M20', name: 'ECOSYS M2000 Series (Mono MFP)' },
            { prefix: 'M', name: 'M Series (ECOSYS MFP)' }
        ]
    },

    /**
     * Brand display names
     */
    BRAND_NAMES: {
        brother: 'Brother',
        canon: 'Canon',
        epson: 'Epson',
        hp: 'HP',
        samsung: 'Samsung',
        lexmark: 'Lexmark',
        oki: 'OKI',
        'fuji-xerox': 'Fuji Xerox',
        kyocera: 'Kyocera'
    },

    /**
     * Group printers by series
     */
    groupPrintersBySeries(printers) {
        const seriesMap = new Map();

        printers.forEach(printer => {
            if (!seriesMap.has(printer.seriesId)) {
                seriesMap.set(printer.seriesId, {
                    id: printer.seriesId,
                    name: printer.seriesName,
                    models: []
                });
            }
            seriesMap.get(printer.seriesId).models.push(printer);
        });

        // Sort models within each series
        seriesMap.forEach(series => {
            series.models.sort((a, b) => a.name.localeCompare(b.name, undefined, { numeric: true }));
        });

        // Convert to array and sort series
        return Array.from(seriesMap.values()).sort((a, b) => {
            if (a.id === 'other') return 1;
            if (b.id === 'other') return -1;
            return a.name.localeCompare(b.name);
        });
    },

    /**
     * Get series for a printer model name
     */
    getSeriesForModel(modelName, brand) {
        const patterns = this.SERIES_PATTERNS[brand] || [];
        for (const pattern of patterns) {
            if (modelName.toUpperCase().startsWith(pattern.prefix.toUpperCase())) {
                // Generate seriesId from series NAME to avoid duplicates
                const seriesId = pattern.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');
                return { id: seriesId, name: pattern.name };
            }
        }
        return { id: 'other', name: 'Other Models' };
    }
};

// Make available globally
window.PrinterData = PrinterData;
