-- =============================================================================
-- analytics_function_grants — RETIRED. THIS FILE GRANTS NOTHING. (ERR-247)
-- =============================================================================
--
-- ⚠️  DO NOT RE-ADD A GRANT HERE, AND DO NOT ASK THE BACKEND TO APPLY THEIR
--     MIGRATION 172. THE BROWSER NO LONGER NEEDS EXECUTE ON ANY OF THESE. ⚠️
--
-- WHAT THIS FILE USED TO DO
--
--   grant execute on function
--     public.analytics_kpi_summary(...), public.analytics_revenue_series(...),
--     public.analytics_refunds_series(...), public.analytics_top_products(...),
--     public.analytics_customer_stats(...), public.analytics_brand_breakdown(...)
--   to authenticated, service_role;
--
-- It existed because the admin Dashboard called those six RPCs DIRECTLY from
-- the browser with the signed-in admin's `authenticated` JWT. Every few weeks a
-- backend migration DROPped and re-CREATEd a function (which discards its ACL)
-- or revoked EXECUTE, the dashboard went dark with `42501 permission denied for
-- function`, and someone pasted this file back in. Four recurrences on the
-- record: ERR-010, ERR-029, ERR-035, ERR-232.
--
-- WHY IT IS GONE RATHER THAN FIXED AGAIN
--
-- The fourth recurrence was not a regression. The grant was revoked ON PURPOSE
-- on 2026-09-07, after a plain customer account read the live P&L
-- (revenue 24189.36 / gross_profit 5124.29 / aov 167.98 / total_customers 135)
-- straight out of PostgREST with the publishable anon key plus its own JWT. The
-- guard inside the functions read
--
--     auth.uid() IS NOT NULL AND NOT is_owner()
--
-- which SKIPS ITSELF when uid is null, so an anonymous caller fell straight
-- through. The bodies were hardened afterwards (they now fail closed); the ACL
-- was deliberately never put back.
--
-- Granting `authenticated` is about six times wider than the need, and every
-- previous round of this was closed exactly that way — which is why there was a
-- fourth. So the backend built the seven server-side routes instead, each
-- behind `requireAdmin` + service_role, and this repo moved onto them:
--
--   analytics_kpi_summary      GET /api/admin/analytics/kpi-summary
--   analytics_revenue_series   GET /api/admin/analytics/revenue-series
--   analytics_refunds_series   GET /api/admin/analytics/refunds-series
--   analytics_customer_stats   GET /api/admin/analytics/customer-stats
--   analytics_top_products     GET /api/admin/analytics/top-products-rpc
--   analytics_brand_breakdown  GET /api/admin/analytics/brand-breakdown
--   get_suppliers              GET /api/admin/analytics/suppliers
--
-- Verified from this repo on 2026-09-12 with a real owner JWT, and with the
-- control that matters — each function called with its REAL named params,
-- because an empty `{}` answers 404 PGRST202 (signature mismatch) and a 404
-- here proves NOTHING:
--
--   POST /rest/v1/rpc/analytics_kpi_summary      -> 403  42501 permission denied
--   POST /rest/v1/rpc/analytics_brand_breakdown  -> 403  42501 permission denied
--   POST /rest/v1/rpc/get_suppliers              -> 403  42501 permission denied
--   GET  /api/admin/analytics/<all seven>        -> 200  with real data
--
-- WHAT A GRANT HERE WOULD COST NOW
--
-- `get_suppliers` was handing the supplier list to ANONYMOUS callers until
-- backend migration 173 (2026-09-10) — only the revoked ACL was holding it
-- shut. And backend migration 165 added two SECURITY DEFINER write RPCs with no
-- internal guard, because the grant WAS the control:
--
--   set_business_contract_price(...)     an arbitrary negotiated price on ANY
--                                        product for ANY business account
--   remove_business_contract_price(...)  delete another account's pricing
--
-- The safety of granting these lives in the FUNCTION BODY, not in the ACL, and
-- backend migration 163 installs an event trigger that re-grants the six
-- automatically on any CREATE/ALTER. So a future redeploy that drops a gate
-- re-opens the P&L with no migration diff to show for it. That risk is only
-- worth carrying if the browser needs the grant. It does not.
--
-- IF THE DASHBOARD GOES DARK AGAIN, IT IS NOT THIS.
-- Check `GET /api/admin/analytics/*` with an owner bearer token. A 401 is an
-- expired sign-in, a 403 is the route's own authorisation, and a 429 is the
-- 20-per-minute limiter that sits on this whole path prefix — all three are
-- reported by name in the UI now (AdminAPI.analyticsHealthSnapshot, ERR-247).
-- None of them is fixed by SQL in this repo.
--
-- LOCATION: repo-root `sql/`, NOT under `inkcartridges/`. That tree is the
--   Vercel project root with `outputDirectory: "."`, so anything in it is
--   served publicly — this file was downloadable at
--   https://www.inkcartridges.co.nz/sql/analytics_function_grants.sql until
--   ERR-229 (Sep 2026). Never move it back. The file is kept (rather than
--   deleted) precisely so this explanation is what the next person finds when
--   they go looking for the grant.
--
-- Project: lmdlgldjgcanknsjrcxh
-- Pinned by tests/analytics-function-grants.test.js.
-- =============================================================================

-- Intentionally no executable SQL below this line.
